version: '3.8'

services:
  metropaccess-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: metropaccess-backend
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - PORT=3000
    volumes:
      - ./data:/app/data
    restart: unless-stopped
